language: node_js
node_js:
  - "node"
branches:
  only:
    - master
cache:
  directories:
  - node_modules/
script: yarn prettier:check && yarn lint && yarn build:check && yarn test && ./test/integration_tests.sh
before_install:
  - if [[ ! $(which expect) ]] ; then sudo apt-get install -y expect ; fi
