language: node_js
env:
  - YARN_GPG=no
os:
  - windows
  - linux
  - osx
node_js:
  - 10
branches:
  only:
    - master
cache:
  directories:
  - node_modules/
script: ./test.sh
addons:
  apt:
    packages:
      - expect
