language: node_js
env:
  - YARN_GPG=no
os:
  - linux
  - osx
node_js:
  - "node"
branches:
  only:
    - master
cache:
  directories:
  - node_modules/
script:  cd packages/dscc-gen && yarn && yarn travis
addons:
  apt:
    packages:
      - expect
