language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "node"
branches:
  only:
    - master
cache:
  directories:
  - node_modules/
script:  yarn travis
addons:
  apt:
    packages:
      - expect
